CREATE TABLE IF NOT EXISTS valute
(
    valuteid    BIGSERIAL PRIMARY KEY ,
    numcode  BIGSERIAL NOT NULL ,
    nominal BIGSERIAL NOT NULL ,
    name VARCHAR(30) NOT NULL ,
    value VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS log
(
    id    BIGSERIAL PRIMARY KEY ,
    date  VARCHAR(200) NOT NULL ,
    course VARCHAR(254) NOT NULL ,
    valute1 VARCHAR(20)  NOT NULL ,
    valute2 VARCHAR(20)  NOT NULL
);